vsamemberstracker/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'events/index'
  # get 'events/new'
  # get 'events/show'
  # get 'events/edit'
  # get 'events/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'member_view#index'
  get 'member_view/index'
  get 'login/index'
  get 'events/login'
  get 'events/logout'
  get 'member_view/login'
  post "login/index" => "login#validate", :as => :LoginAttempt
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    member do
      get :delete
    end
  end

  resources :households do
    collection { post :import }
  end
end

vsamemberstracker/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

vsamemberstracker/app/models/backup.rb
# frozen_string_literal: true

class Backup < ApplicationRecord
end

vsamemberstracker/app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :name, presence: true
end

vsamemberstracker/app/models/household.rb
# frozen_string_literal: true

class Household < ApplicationRecord
  def self.import(file)
    file = file.path if file.is_a?(File)
    CSV.foreach(file, headers: true) do |row|
      Household.create row.to_hash
    end
  end
end

vsamemberstracker/app/models/login_attempt.rb
# frozen_string_literal: true

class LoginAttempt < ApplicationRecord
end

vsamemberstracker/app/models/rail.rb
# frozen_string_literal: true

class Rail < ApplicationRecord
end

vsamemberstracker/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

vsamemberstracker/app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  layout false
  $adminBOOLEAN = 0


  def index
    @events = Event.order('name ASC')
    if($adminBOOLEAN == 1)
        render('index')
    else
        redirect_to(controller: 'member_view', action: 'index')
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    flash[:added] = 'you have added an event'
    redirect_to(events_path)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to(event_path(@event))
    else
      render('edit')
    end
  end

  def delete
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to(events_path)
  end

  def login
    redirect_to(controller: 'login', action: 'index')
  end

  def logout
      $adminBOOLEAN = 0
      redirect_to(controller: 'member_view', action: 'index')
    end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :time, :points)
  end
end

vsamemberstracker/app/controllers/households_controller.rb
# frozen_string_literal: true

class HouseholdsController < ApplicationController
  before_action :set_household, only: %i[show edit update destroy]

  # GET /households or /households.json
  def index
    @households = Household.all
  end

  # GET /households/1 or /households/1.json
  def show; end

  # GET /households/new
  def new
    @household = Household.new
  end

  # GET /households/1/edit
  def edit; end

  # POST /households or /households.json
  def create
    @household = Household.new(household_params)

    respond_to do |format|
      if @household.save
        format.html { redirect_to @household, notice: 'Household was successfully created.' }
        format.json { render :show, status: :created, location: @household }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /households/1 or /households/1.json
  def update
    respond_to do |format|
      if @household.update(household_params)
        format.html { redirect_to @household, notice: 'Household was successfully updated.' }
        format.json { render :show, status: :ok, location: @household }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1 or /households/1.json
  def destroy
    @household.destroy
    respond_to do |format|
      format.html { redirect_to households_url, notice: 'Household was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Household.import(params[:file])
    redirect_to households_path, notice: 'households added sucessfully'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_household
    @household = Household.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def household_params
    params.require(:household).permit(:first, :last, :UIN, :family, :email, :phonenumber, :classification, :major)
  end
end

vsamemberstracker/app/controllers/login_controller.rb
# frozen_string_literal: true

class LoginController < ApplicationController
  layout false
  require 'events_controller'

#  def index
#    @login_attempt = LoginAttempt.all
#  end

#  def new
#    @login_attempt = LoginAttempt.new
#  end

#  def edit
#    @login_attempt = LoginAttempt.find(params[:id])
#  end

#  def create
#    @login_attempt = LoginAttempt.new(
#      username: params[:LoginAttempt][:username],
#      password: params[:LoginAttempt][:password]
#    )
#    @login_attempt.save
#  end

  def validate
    #validate action
    @login_attempt = LoginAttempt.new(login_attempt_params)
    #puts "------HERE-------" + @login_attempt.username
    @username = "cat"
    @password = "dog"



    if @login_attempt.username == @username && @login_attempt.password == @password
      $adminBOOLEAN = 1
      redirect_to(controller: 'events', action: 'index')
    else
      redirect_to(controller: 'login', action: 'index')
    end
  end

  def login
    # render('login')
  end


#  def adminView
#
#    #render('adminView')
#  end


  private

  def login_attempt_params
    params.require(:LoginAttempt).permit(:username, :password)
  end
end

# to pass data from controller to view, use instance variables
# @variable

vsamemberstracker/app/controllers/member_view_controller.rb
class MemberViewController < ApplicationController
  layout false
  def index
      @events = Event.order('name ASC')
  end

  def show
      @event = Event.find(params[:id])
  end

  def login
    redirect_to(controller: 'login', action: 'index')
  end

  private

      def event_params
        params.require(:event).permit(:name, :description, :location, :time, :points)
      end
end

vsamemberstracker/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

vsamemberstracker/app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

vsamemberstracker/app/helpers/households_helper.rb
# frozen_string_literal: true

module HouseholdsHelper
end

vsamemberstracker/app/views/events/delete.html.erb
<%= link_to("<< Back to Home", events_path, :class => 'back-link') %>
<%= image_tag ("vsa.png") %>
<div class="events delete">
  <h2>Delete event</h2>

  <%= form_for(@event, :method => 'delete') do |f| %>


    <p>You sure you want to delete the event?</p>

    <div class="form-buttons">
      <%= f.submit("Delete event") %>
    </div>

  <% end %>
</div>

vsamemberstracker/app/views/events/edit.html.erb
<%= link_to("<< Back to Home", events_path, :class => 'back-link') %>
<%= image_tag ("vsa.png") %>
<div class="event show">
  <h2>Update Event </h2>

<%= form_for(@event) do |e| %>
  <table summary="book form">
    <tr>
      <th>Title</th>
      <td><%= e.text_field(:name) %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= e.text_field(:description) %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= e.text_field(:location) %></td>
    </tr>
    <tr>
      <th>Time</th>
      <td><%= e.text_field(:time) %></td>
    </tr>
    <tr>
      <th>Points</th>
      <td><%= e.text_field(:points) %></td>
    </tr>
  </table>


  <div class = "form-buttons">
    <%= e.submit("Update Event")%>
    </div>
<% end %>
</div>

vsamemberstracker/app/views/events/index.html.erb
<div class= "events index">
  <%= image_tag ("vsa.png") %>
  <h2>VSA Events</h2>
  <p>View all the events in our club</p>
  <table class="listing" summary="events list">
    <tr class="header">
      <th>Events</th>
      <th>Description</th>
      <th>Location</th>
      <th>Time</th>
      <th>Points</th>

    </tr>
    <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.description %></td>
      <td><%= event.location %></td>
      <td><%= event.time %></td>
      <td><%= event.points %></td>
        <td class="actions">
        <%= link_to("Details", event_path(event), :class => 'action show') %>
        <%= link_to("Update", edit_event_path(event), :class => 'action edit') %>
        <%= link_to("Delete", delete_event_path(event), :class => 'action delete') %>
      </td>
    </tr>


    <% end %>
  </table>
  </br>
    <div class = "form-buttons">
      <%= button_to("Logout", { :action => "logout" }, :method => :get, :class => 'login new') %>
  </div>

    <div class = "form-buttons">
        <%= button_to("Add a new event", { :action => "new" }, :method => :get, :class => 'action new') %>
    </div>
      <div class = "form-buttons">
        <%= button_to("Add a new household", households_path, :method => :get) %>
    </div>


    <% flash.each do |key, value| %>
      <td><%= value%> </td>
    <%end%>
</div>

vsamemberstracker/app/views/events/new.html.erb
  
<%= link_to("<< Back to Home", events_path, :class => 'back-link') %>
<%= image_tag ("vsa.png") %>
<div class="event show">
  <h2>Add an event</h2>

<%= form_for(@event, :url => events_path, :method => 'post') do |e| %>
  <table summary="event form">
    <tr>
      <th>Name</th>
      <td><%= e.text_field(:name) %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= e.text_field(:description) %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= e.text_field(:location) %></td>
    </tr>
    <tr>
      <th>Time</th>
      <td><%= e.text_field(:time) %></td>
    </tr>
    <tr>
      <th>Points</th>
      <td><%= e.text_field(:points) %></td>
    </tr>

  </table>

  <div class = "form-buttons">
    <%= e.submit("Add Event")%>
    </div>
<% end %>
</div>

vsamemberstracker/app/views/events/show.html.erb
<%= link_to("<< Back to Home", events_path, :class => 'back-link') %>
<%= image_tag ("vsa.png") %>
<div class="book show">
  <h2>Details about '<%= @event.name %>'</h2>

  <table summary="book detail view">
    <tr>
      <th>Name</th>
      <td><%= @event.name %></td>
    </tr>
    <tr>
      <th>Decscription</th>
      <td><%= @event.description %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= @event.location %></td>
    </tr>
    <tr>
      <th>Time</th>
      <td><%= @event.time %></td>
    </tr>
    <tr>
      <th>Points</th>
      <td><%= @event.points %></td>
    </tr>

  </table>

</div>

vsamemberstracker/app/views/households/_form.html.erb
<%= form_with(model: household) do |form| %>
  <% if household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
        <% household.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="field">
    <%= form.label :UIN %>
    <%= form.text_field :UIN %>
  </div>

  <div class="field">
    <%= form.label :family %>
    <%= form.text_field :family %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phonenumber %>
    <%= form.text_field :phonenumber %>
  </div>

  <div class="field">
    <%= form.label :classification %>
    <%= form.text_field :classification %>
  </div>

  <div class="field">
    <%= form.label :major %>
    <%= form.text_field :major %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

vsamemberstracker/app/views/households/edit.html.erb
<h1>Editing Household</h1>

<%= render 'form', household: @household %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

vsamemberstracker/app/views/households/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Households</h1>
<%= link_to("<< Back to Home", events_path, :class => 'back-link') %>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>First</th>
          <th>Last</th>
          <th>Uin</th>
          <th>Family</th>
          <th>Email</th>
          <th>Phonenumber</th>
          <th>Classification</th>
          <th>Major</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @households.each do |household| %>
          <tr>
            <td><%= household.first %></td>
            <td><%= household.last %></td>
            <td><%= household.UIN %></td>
            <td><%= household.family %></td>
            <td><%= household.email %></td>
            <td><%= household.phonenumber %></td>
            <td><%= household.classification %></td>
            <td><%= household.major %></td>
            <td><%= link_to 'Show', household %></td>
            <td><%= link_to 'Edit', edit_household_path(household) %></td>
            <td><%= link_to 'Destroy', household, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>
<h3>Import household</h3>
<div class = import>
  <%= form_tag import_households_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Upload Households"%>
  <% end %>
</div>
<%= link_to 'New Household', new_household_path %>

vsamemberstracker/app/views/households/new.html.erb
<h1>New Household</h1>

<%= render 'form', household: @household %>

<%= link_to 'Back', households_path %>

vsamemberstracker/app/views/households/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @household.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @household.last %>
</p>

<p>
  <strong>Uin:</strong>
  <%= @household.UIN %>
</p>

<p>
  <strong>Family:</strong>
  <%= @household.family %>
</p>

<p>
  <strong>Email:</strong>
  <%= @household.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @household.phonenumber %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @household.classification %>
</p>

<p>
  <strong>Major:</strong>
  <%= @household.major %>
</p>

<%= link_to 'Edit', edit_household_path(@household) %> |
<%= link_to 'Back', households_path %>

vsamemberstracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vsamemberstracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

vsamemberstracker/app/views/login/index.html.erb
<h1><%= link_to 'Continue as a club member', "/member_view/index" %></h1>



<h1>Admin Login</h1>

<%= form_for(:LoginAttempt) do |f| %>
  username: <%= f.text_field (:username) %><br />
  password: <%= f.text_field (:password) %><br />
  <%= f.submit 'submit'%>
<% end %>

vsamemberstracker/app/views/member_view/index.html.erb
<div class= "events index">
  <%= image_tag ("vsa.png") %>
  <h2>VSA Events</h2>
  <p>View all the events in our club</p>
  <table class="listing" summary="events list">
    <tr class="header">
      <th>Events</th>
      <th>Description</th>
      <th>Location</th>
      <th>Time</th>
      <th>Points</th>

    </tr>
    <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.description %></td>
      <td><%= event.location %></td>
      <td><%= event.time %></td>
      <td><%= event.points %></td>
        <td class="actions">
        <%= link_to("Details", event_path(event), :class => 'action show') %>
      </td>
    </tr>


    <% end %>
  </table>
  </br>
    <div class = "form-buttons">
      <%= button_to("Administrator Login", { :action => "login" }, :method => :get, :class => 'login new') %>
  </div>




    <% flash.each do |key, value| %>
      <td><%= value%> </td>
    <%end%>
</div>